//
//  TVShowInfoPresenter.swift
//  StarsPlayChallenge
//
//  Created by Matloob on 10/9/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TVShowInfoPresentationLogic
{
    func presentTVShowResponse(response: TVShowInfo.TVShow.Response)
    func presentSeasonDetailResponse(response: SeasonInfo.seasonDetail.Response)
}

class TVShowInfoPresenter: TVShowInfoPresentationLogic
{
    
    
    weak var viewController: TVShowInfoDisplayLogic?
    
    func presentTVShowResponse(response: TVShowInfo.TVShow.Response) {
        let viewModel = TVShowInfo.TVShow.ViewModel(tvShowDetail: response.tvShowDetail)
        viewController?.presentShowDetail(viewModel: viewModel)
    }
    
    func presentSeasonDetailResponse(response: SeasonInfo.seasonDetail.Response) {
        let viewModel = SeasonInfo.seasonDetail.ViewModel(seasonModel: response.seasonModel)
        viewController?.presentSeasonDetail(viewModel: viewModel)
    }
    
    
    
    
    
    
    
    
    // MARK: Do something
    
    //  func presentSomething(response: TVShowInfo.TVShow.Response)
    //  {
    //    let viewModel = TVShowInfo.TVShow.ViewModel()
    //    viewController?.displaySomething(viewModel: viewModel)
    //  }
}
