//
//  TVShowInfoModels.swift
//  StarsPlayChallenge
//
//  Created by Matloob on 10/9/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum TVShowInfo
{
    // MARK: Use cases
    
    enum TVShow
    {
        struct Request
        {
            var tv_id: String?
        }
        struct Response
        {
            var tvShowDetail: TVShowBase?
        }
        struct ViewModel
        {
            // Here we add only those variable, we need to show on screen. but currently due to time constraint and not much info about extra fields are coming so I am adding whole base object in view model as well
            var tvShowDetail:TVShowBase?
        }
    }
}


enum SeasonInfo
{
    // MARK: Use cases
    
    enum seasonDetail
    {
        struct Request
        {
            var tv_id: String?
            var season_number: String?
        }
        struct Response
        {
            var seasonModel: SeasonModel?
        }
        struct ViewModel
        {
            // Here we add only those variable, we need to show on screen. but currently due to time constraint and not much info about extra fields are coming so I am adding whole base object in view model as well
            var seasonModel: SeasonModel?
        }
    }
}
